asimeo2exam2: lab10Main.o lab10List.o
	g++ -o asimeo2exam2 lab10Main.o lab10List.o

lab10Main.o: lab10Main.cpp lab10List.h
	g++ -c lab10Main.cpp

lab10List.o: lab10List.cpp lab10List.h
	g++ -c lab10List.cpp

clean:
	rm asimeo2exam2*.o asimeo2exam2
